# To run locally
# npx @techdocs/cli serve -v -c ./mkdocs.yml
# 
site_name: 'k6-jslib-summary Internal Documentation'
repo_url: https://github.com/grafana/k6-jslib-summary
edit_uri: edit/main/docs

theme:
  name: material
  features:
    - navigation.sections

plugins:
  - techdocs-core
