name: "Auto assign maintainer to issue"
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  assign-maintainer:
    uses: grafana/k6/.github/workflows/issue-auto-assign.yml@40935d43dc9034a29610d38af37db25101d86e13 # master
